---
    - name: Ensure ~/grafana directory exists
      file:
        path: "{{ grafana_dir }}"
        state: directory
        mode: '0755'

    - name: Copy grafana_prometheus_node.yml from remote server to ~/grafana
      copy:
        src: grafana_prometheus_node.yml
        dest: "{{ grafana_dir }}/docker-compose.yml"
    
    - name: Deny access to udp port 9100 from host {{ main_monitoring_server }} and include a comment
      ufw:
        rule: allow
        proto: tcp
        src: "{{ main_server }}"
        port: '9100'
        comment: "node_exporter -> only {{ main_monitoring_server }}"

    - name: Full setup Grafana, Prometheus, Exporter
      import_tasks: full_monitoring.yml
      when: main_monitoring_server == ansible_host

    - name: Setup only Exporter 
      shell: docker compose up -d node_exporter
      args:
        chdir: "{{ grafana_dir }}"
      when: main_monitoring_server != ansible_host