network: sei_devnet
folder: '.sei'
daemon: seid
chain_id: 'sei-devnet-3'
node_version: '3.0.0'
repo: https://github.com/sei-protocol/sei-chain.git
genesis: https://raw.githubusercontent.com/sei-protocol/testnet/main/sei-devnet-3/genesis.json
peers: '8c5d3a09dd5b67a270e89c16e0a4836b1c284261@3.73.138.242:26656,40f11eb47a2d3b8e1eb014050b75ef8a3b2697de@162.19.232.153:51956,84a6b647e8845c6fbb5b26fba5d8401485fd6263@136.243.88.91'
custom_port_prefix: 119
upgrade_folder: 3.0.0

# [Optional] Snapshot
snapshot_hour: 2
snapshot_minute: 0
wasm: 'outside'

# price feeder
price_feeder_address: 'sei1xm4gqdpyfqerm42w045mgdqfs5cqye576xeg6x'
price_feeder_validator: 'seivaloper1qnn8rvtlfya3u4qvryqtjnc6gum4ltajvgyjam'
price_feeder_backend: os
price_feeder_network: devnet
