- hosts: all
  become: yes
  tasks:
    - name: Ensure ~/.script_node directory exists
      file:
        path: "{{ user_dir }}/.script_node"
        state: directory
        owner: "{{ ansible_user }}"
        mode: '0755'

    - name: Copy disk_monitoring.sh script to ~/.script_node
      copy:
        src: disk_monitoring.sh
        dest: "{{ user_dir }}/.script_node/disk_monitoring.sh"
        mode: '0755'
        owner: "{{ ansible_user }}"

    - name: Add cron job for disk monitoring script (5:00 and 19:00)
      cron:
        name: "Disk monitoring script"
        minute: "0"
        hour: "5,19"
        job: "{{ user_dir }}/.script_node/disk_monitoring.sh {{ monitoring_disk }}"
        user: "{{ ansible_user }}"
