---
- name: Install or Update Go
  hosts: all
  become: yes
  tasks:
    - name: Download and execute the Go {{ go_version}} update script 
      shell: |
        bash -c "$(curl -fsSL https://raw.githubusercontent.com/ToTheMars2/Update_programs/main/update_go.sh)" -- "{{ go_version }}" "{{ user_dir }}" 
      args:
        executable: /bin/bash
      register: update_result
      failed_when: update_result.rc != 0
      changed_when: "'Go version' in update_result.stdout"

    - name: Print Go installation result
      debug:
        var: update_result.stdout